/*
 * Piece_Together_Animation.asm
 *
 *  Created: 4/10/2017 11:37:12 AM
 *   Author: qbake_0
 */ 
 ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Piece_Together:																																											;
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAA																																									;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp																	;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp																    ;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp																    ;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp																	;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp																	;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp																	;
																																														;
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAE																																									;										
		ldi temp, 0x40 ST X, temp Call D1 ldi Xl, 0xAE ldi temp, 0x10 ST X, temp Call D1 ldi Xl, 0xB0 ldi temp, 0x10 ST X, temp Call D1 ldi Xl, 0xAF ldi temp, 0x40 ST X, temp Call D1	;
		ldi Xl, 0xAE																																									;
		ldi temp, 0x01 ST X, temp Call D1 ldi Xl, 0xB0 ldi temp, 0x04 ST X, temp Call D1 ldi Xl, 0xAF ldi temp, 0x04 ST X, temp Call D1 ldi Xl, 0xB1 ldi temp, 0x01 ST X, temp Call D1	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAE																																									;										
		ldi temp, 0x04 ST X, temp Call D1 ldi Xl, 0xB0 ldi temp, 0x01 ST X, temp Call D1 ldi Xl, 0xAF ldi temp, 0x01 ST X, temp Call D1 ldi Xl, 0xB0 ldi temp, 0x40 ST X, temp Call D1	;
		ldi Xl, 0xAE																																									;
		ldi temp, 0x20 ST X, temp Call D1 ldi Xl, 0xAF ldi temp, 0x10 ST X, temp Call D1 ldi Xl, 0xAE ldi temp, 0x02 ST X, temp Call D1 ldi Xl, 0xB0 ldi temp, 0x80 ST X, temp Call D1	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAF																																									;										
		ldi temp, 0x08 ST X, temp Call D1 ldi Xl, 0xAE ldi temp, 0x08 ST X, temp Call D1 ldi Xl, 0xB0 ldi temp, 0x02 ST X, temp Call D1 ldi Xl, 0xAF ldi temp, 0x02 ST X, temp Call D1	;
		ldi Xl, 0xAF																																									;
		ldi temp, 0x80 ST X, temp Call D1 ldi Xl, 0xAE ldi temp, 0x80 ST X, temp Call D1 ldi Xl, 0xB0 ldi temp, 0x08 ST X, temp Call D1 ldi Xl, 0xB0 ldi temp, 0x20 ST X, temp Call D1	;
		ldi XL, 0xAF ldi temp, 0x20 ST X, temp Call D1																																	;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAE																																									;										
		ldi temp, 0x40 ST X, temp Call D2 ldi Xl, 0xAE ldi temp, 0x10 ST X, temp Call D2 ldi Xl, 0xB0 ldi temp, 0x10 ST X, temp Call D2 ldi Xl, 0xAF ldi temp, 0x40 ST X, temp Call D2	;
		ldi Xl, 0xAE																																									;
		ldi temp, 0x01 ST X, temp Call D2 ldi Xl, 0xB0 ldi temp, 0x04 ST X, temp Call D2 ldi Xl, 0xAF ldi temp, 0x04 ST X, temp Call D2 ldi Xl, 0xB1 ldi temp, 0x01 ST X, temp Call D2	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAE																																									;										
		ldi temp, 0x04 ST X, temp Call D2 ldi Xl, 0xB0 ldi temp, 0x01 ST X, temp Call D2 ldi Xl, 0xAF ldi temp, 0x01 ST X, temp Call D2 ldi Xl, 0xB0 ldi temp, 0x40 ST X, temp Call D2	;
		ldi Xl, 0xAE																																									;
		ldi temp, 0x20 ST X, temp Call D2 ldi Xl, 0xAF ldi temp, 0x10 ST X, temp Call D2 ldi Xl, 0xAE ldi temp, 0x02 ST X, temp Call D2 ldi Xl, 0xB0 ldi temp, 0x80 ST X, temp Call D2	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAF																																									;										
		ldi temp, 0x08 ST X, temp Call D2 ldi Xl, 0xAE ldi temp, 0x08 ST X, temp Call D2 ldi Xl, 0xB0 ldi temp, 0x02 ST X, temp Call D2 ldi Xl, 0xAF ldi temp, 0x02 ST X, temp Call D2	;
		ldi Xl, 0xAF																																									;
		ldi temp, 0x80 ST X, temp Call D2 ldi Xl, 0xAE ldi temp, 0x80 ST X, temp Call D2 ldi Xl, 0xB0 ldi temp, 0x08 ST X, temp Call D2 ldi Xl, 0xB0 ldi temp, 0x20 ST X, temp Call D2	;
		ldi XL, 0xAF ldi temp, 0x20 ST X, temp Call D2																																	;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAE																																									;										
		ldi temp, 0x40 ST X, temp Call D3 ldi Xl, 0xAE ldi temp, 0x10 ST X, temp Call D3 ldi Xl, 0xB0 ldi temp, 0x10 ST X, temp Call D3 ldi Xl, 0xAF ldi temp, 0x40 ST X, temp Call D3	;
		ldi Xl, 0xAE																																									;
		ldi temp, 0x01 ST X, temp Call D3 ldi Xl, 0xB0 ldi temp, 0x04 ST X, temp Call D3 ldi Xl, 0xAF ldi temp, 0x04 ST X, temp Call D3 ldi Xl, 0xB1 ldi temp, 0x01 ST X, temp Call D3	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAE																																									;										
		ldi temp, 0x04 ST X, temp Call D3 ldi Xl, 0xB0 ldi temp, 0x01 ST X, temp Call D3 ldi Xl, 0xAF ldi temp, 0x01 ST X, temp Call D3 ldi Xl, 0xB0 ldi temp, 0x40 ST X, temp Call D3	;
		ldi Xl, 0xAE																																									;
		ldi temp, 0x20 ST X, temp Call D3 ldi Xl, 0xAF ldi temp, 0x10 ST X, temp Call D3 ldi Xl, 0xAE ldi temp, 0x02 ST X, temp Call D3 ldi Xl, 0xB0 ldi temp, 0x80 ST X, temp Call D3	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAF																																									;										
		ldi temp, 0x08 ST X, temp Call D3 ldi Xl, 0xAE ldi temp, 0x08 ST X, temp Call D3 ldi Xl, 0xB0 ldi temp, 0x02 ST X, temp Call D3 ldi Xl, 0xAF ldi temp, 0x02 ST X, temp Call D3	;
		ldi Xl, 0xAF																																									;
		ldi temp, 0x80 ST X, temp Call D3 ldi Xl, 0xAE ldi temp, 0x80 ST X, temp Call D3 ldi Xl, 0xB0 ldi temp, 0x08 ST X, temp Call D3 ldi Xl, 0xB0 ldi temp, 0x20 ST X, temp Call D3	;
		ldi XL, 0xAF ldi temp, 0x20 ST X, temp Call D3																																	;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAE																																									;										
		ldi temp, 0x40 ST X, temp Call D4 ldi Xl, 0xAE ldi temp, 0x10 ST X, temp Call D4 ldi Xl, 0xB0 ldi temp, 0x10 ST X, temp Call D4 ldi Xl, 0xAF ldi temp, 0x40 ST X, temp Call D4	;
		ldi Xl, 0xAE																																									;
		ldi temp, 0x01 ST X, temp Call D4 ldi Xl, 0xB0 ldi temp, 0x04 ST X, temp Call D4 ldi Xl, 0xAF ldi temp, 0x04 ST X, temp Call D4 ldi Xl, 0xB1 ldi temp, 0x01 ST X, temp Call D4	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAE																																									;										
		ldi temp, 0x04 ST X, temp Call D4 ldi Xl, 0xB0 ldi temp, 0x01 ST X, temp Call D4 ldi Xl, 0xAF ldi temp, 0x01 ST X, temp Call D4 ldi Xl, 0xB0 ldi temp, 0x40 ST X, temp Call D4	;
		ldi Xl, 0xAE																																									;
		ldi temp, 0x20 ST X, temp Call D4 ldi Xl, 0xAF ldi temp, 0x10 ST X, temp Call D4 ldi Xl, 0xAE ldi temp, 0x02 ST X, temp Call D4 ldi Xl, 0xB0 ldi temp, 0x80 ST X, temp Call D4	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAF																																									;										
		ldi temp, 0x08 ST X, temp Call D4 ldi Xl, 0xAE ldi temp, 0x08 ST X, temp Call D4 ldi Xl, 0xB0 ldi temp, 0x02 ST X, temp Call D4 ldi Xl, 0xAF ldi temp, 0x02 ST X, temp Call D4	;
		ldi Xl, 0xAF																																									;
		ldi temp, 0x80 ST X, temp Call D4 ldi Xl, 0xAE ldi temp, 0x80 ST X, temp Call D4 ldi Xl, 0xB0 ldi temp, 0x08 ST X, temp Call D4 ldi Xl, 0xB0 ldi temp, 0x20 ST X, temp Call D4	;
		ldi XL, 0xAF ldi temp, 0x20 ST X, temp Call D4																																	;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAA																																									;										
		ldi temp, 0x40 ST X, temp Call D5 ldi Xl, 0xAA ldi temp, 0x10 ST X, temp Call D5 ldi Xl, 0xAC ldi temp, 0x10 ST X, temp Call D5 ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call D5	;
		ldi Xl, 0xAA																																									;
		ldi temp, 0x01 ST X, temp Call D5 ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call D5 ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call D5 ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call D5	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAA																																									;										
		ldi temp, 0x04 ST X, temp Call D5 ldi Xl, 0xAC ldi temp, 0x01 ST X, temp Call D5 ldi Xl, 0xAB ldi temp, 0x01 ST X, temp Call D5 ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call D5	;
		ldi Xl, 0xAA																																									;
		ldi temp, 0x20 ST X, temp Call D5 ldi Xl, 0xAB ldi temp, 0x10 ST X, temp Call D5 ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call D5 ldi Xl, 0xAC ldi temp, 0x80 ST X, temp Call D5	;
																																														;		
		ldi Xh, 0x00																																									;
		ldi Xl, 0xAB																																									;										
		ldi temp, 0x08 ST X, temp Call D5 ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call D5 ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call D5 ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call D5	;
		ldi Xl, 0xAB																																									;
		ldi temp, 0x80 ST X, temp Call D5 ldi Xl, 0xAA ldi temp, 0x80 ST X, temp Call D5 ldi Xl, 0xAC ldi temp, 0x08 ST X, temp Call D5 ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call D5	;
		ldi XL, 0xAB ldi temp, 0x20 ST X, temp Call D5 Call D5 Call D5																													;
		ldi temp_3, 85 ldi counter, 100 call bright																																		;
		RET																																												;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////																																														
D1:																															;
		ldi Subtraction4, 5																									;
Piece_Together_loop:																												;
		ldi temp_3, 85 ldi counter, 4 call bright																			;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBA																										;
		ld Byte_1, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBE																										;
		ld temp, X																											;
		OR Byte_1, temp																										;
		ST X, Byte_1																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBB																										;
		ld Byte_2, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBF																										;
		ld temp, X																											;
		OR Byte_2, temp																										;
		ST X, Byte_2																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBC																										;
		ld Byte_3, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xC0																										;
		ld temp, X																											;
		OR Byte_3, temp																										;
		ST X, Byte_3																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBD																										;
		ld Byte_4, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xC1																										;
		ld temp, X																											;
		OR Byte_4, temp																										;
		ST X, Byte_4																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB6																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
																															;
		ldi Subtraction3, 1																									;
		CP Subtraction4, Subtraction3																						;
		BREQ Piece_Together_end																									;
		DEC Subtraction4																									;
		rjmp Piece_Together_loop																									;
Piece_Together_end:																												;
		ldi temp_3, 85 ldi counter, 4 call bright																			;		
		RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
D2:																															;
		ldi Subtraction4, 4																									;
Piece_Together2_loop:																												;
		ldi temp_3, 85 ldi counter, 4 call bright																			;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB6																										;
		ld Byte_1, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBA																										;
		ld temp, X																											;
		OR Byte_1, temp																										;
		ST X, Byte_1																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB7																										;
		ld Byte_2, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBB																										;
		ld temp, X																											;
		OR Byte_2, temp																										;
		ST X, Byte_2																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB8																										;
		ld Byte_3, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBC																										;
		ld temp, X																											;
		OR Byte_3, temp																										;
		ST X, Byte_3																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB9																										;
		ld Byte_4, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBD																										;
		ld temp, X																											;
		OR Byte_4, temp																										;
		ST X, Byte_4																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
																															;
		ldi Subtraction3, 1																									;
		CP Subtraction4, Subtraction3																						;
		BREQ Piece_Together2_end																									;
		DEC Subtraction4																									;
		rjmp Piece_Together2_loop																									;
Piece_Together2_end:																												;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp_3, 85 ldi counter, 4 call bright																			;
		RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
D3:																															;
		ldi Subtraction4, 3																									;
Piece_Together3_loop:																												;
		ldi temp_3, 85 ldi counter, 4 call bright																			;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ld Byte_1, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB6																										;
		ld temp, X																											;
		OR Byte_1, temp																										;
		ST X, Byte_1																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB3																										;
		ld Byte_2, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB7																										;
		ld temp, X																											;
		OR Byte_2, temp																										;
		ST X, Byte_2																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB4																										;
		ld Byte_3, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB8																										;
		ld temp, X																											;
		OR Byte_3, temp																										;
		ST X, Byte_3																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB5																										;
		ld Byte_4, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB9																										;
		ld temp, X																											;
		OR Byte_4, temp																										;
		ST X, Byte_4																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
																															;
		ldi Subtraction3, 1																									;
		CP Subtraction4, Subtraction3																						;
		BREQ Piece_Together3_end																									;
		DEC Subtraction4																									;
		rjmp Piece_Together3_loop																									;
Piece_Together3_end:																												;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp_3, 85 ldi counter, 4 call bright																			;
		RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
D4:																															;
		ldi Subtraction4, 2																									;
Piece_Together4_loop:																												;
		ldi temp_3, 85 ldi counter, 8 call bright																			;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ld Byte_1, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ld temp, X																											;
		OR Byte_1, temp																										;
		ST X, Byte_1																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAF																										;
		ld Byte_2, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB3																										;
		ld temp, X																											;
		OR Byte_2, temp																										;
		ST X, Byte_2																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB0																										;
		ld Byte_3, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB4																										;
		ld temp, X																											;
		OR Byte_3, temp																										;
		ST X, Byte_3																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB1																										;
		ld Byte_4, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB5																										;
		ld temp, X																											;
		OR Byte_4, temp																										;
		ST X, Byte_4																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
																															;
		ldi Subtraction3, 1																									;
		CP Subtraction4, Subtraction3																						;
		BREQ Piece_Together4_end																									;
		DEC Subtraction4																									;
		rjmp Piece_Together4_loop																									;
Piece_Together4_end:																												;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp_3, 85 ldi counter, 8 call bright																			;
		RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
D5:																															;
		ldi Subtraction4, 1																									;
Piece_Together5_loop:																												;
		ldi temp_3, 85 ldi counter, 8 call bright																			;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ld Byte_1, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ld temp, X																											;
		OR Byte_1, temp																										;
		ST X, Byte_1																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAB																										;
		ld Byte_2, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAF																										;
		ld temp, X																											;
		OR Byte_2, temp																										;
		ST X, Byte_2																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAC																										;
		ld Byte_3, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB0																										;
		ld temp, X																											;
		OR Byte_3, temp																										;
		ST X, Byte_3																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAD																										;
		ld Byte_4, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB1																										;
		ld temp, X																											;
		OR Byte_4, temp																										;
		ST X, Byte_4																										;
																															;
		ldi Subtraction3, 1																									;
		CP Subtraction4, Subtraction3																						;
		BREQ Piece_Together5_end																									;
		DEC Subtraction4																									;
		rjmp Piece_Together5_loop																									;
Piece_Together5_end:																												;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ldi temp_3, 85 ldi counter, 8 call bright																			;
		RET																													;
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////